# Error Handling

- 구독자에게 error가 전달되면 구독이 종료.
    - ex) UI Update의 경우
- catchError or Retry

## catchError, catchErrorJustReturn

- 네트워크 응답에서 많이 사용
- 로컬캐쉬 또는 기본값 전달하는 방식으로 처리 가능.
- Error의 기본값이 있을 경우는 사용 catchErrorJustReturn

```swift
// #catchError
enum MyError: Error {
   case error
}

let subject = PublishSubject<Int>()
let recovery = PublishSubject<Int>()

subject
    .catchError { _ in recovery}
   .subscribe { print($0) }
   .disposed(by: bag)

subject.onError(MyError.error)
subject.onNext(3)
recovery.onNext(4)
recovery.onCompleted()

// #catchErrorJustReturn
enum MyError: Error {
   case error
}

let subject = PublishSubject<Int>()
let recovery = PublishSubject<Int>()

subject
    .catchErrorJustReturn(-1)
   .subscribe { print($0) }
   .disposed(by: bag)

subject.onError(MyError.error)
```

## Retry, retryWhen

- 에러가 발생할 경우 새로운 옵저버블을 구독 시작.
- 재시도 횟수는 1을 더해야함.
- retryWhen: 사용자가 동작을 할때만 재시도 ( trigger 발생 )

```swift
let bag = DisposeBag()

enum MyError: Error {
   case error
}

var attempts = 1

let source = Observable<Int>.create { observer in
   let currentAttempts = attempts
   print("START #\(currentAttempts)")
   
   if attempts < 3 {
      observer.onError(MyError.error)
      attempts += 1
   }
   
   observer.onNext(1)
   observer.onNext(2)
   observer.onCompleted()
   
   return Disposables.create {
      print("END #\(currentAttempts)")
   }
}

let trigger = PublishSubject<Void>()

source
//    .retry(3)
    .retryWhen { _ in trigger } // trigger를 통해서 시도
    .subscribe { print($0) }
    .disposed(by: bag)

trigger.onNext(())
trigger.onNext(())
```